---
title: "cleaning data"
author: "Vadym Yudenko"
format: html
editor: visual
---

```{r}
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE
)
```


```{r}
packages <- c("lattice", 
              "tidyverse", 
              "likert", 
              "MASS", 
              "psych",
              "viridis", 
              "ggplot2", 
              "here",
              "flextable", 
              "devtools", 
              "GPArotation",
              "ufs", 
              "remotes",
              "ggplot2",
              "ggExtra",
              "ggthemes",
              "gtsummary",
              "hrbrthemes",
              "scales",
              "stargazer",
              "fastDummies")

install_missing_packages <- function(package) {
  if (!require(package, character.only = TRUE)) {
    install.packages(package)
  }
}

lapply(packages, install_missing_packages)
```


```{r}
data <- read_csv("D:/KSE/Projects/ukraine_discounting/data/survey_data.csv")

#removing timestamp, feedback and introduction sections
data <- data[,-c(1,2,48)]

# renaming columns
colnames <- c(
  "Q1",
  "Q1_now_1",
  "Q1_now_2",
  "Q1_wait_1",
  "Q1_wait_2",
  "Q2",
  "Q2_wait_1",
  "Q2_wait_2",
  "Q2_now_1",
  "Q2_now_2",
  "Q3_gain_time",
  "Q4_loss_time",
  "Q5_framing",
  "Q6_magnitude",
  "Q7_prob",
  "Q8_spending",
  "Q9_vacation_or_pay",
  "Q10_fin_expectation",
  "Q11_income",
  "Q12_war_fin_wellbeing",
  "Q13_debts",
  "Q14_family_fin_wellbeing",
  "Q15_birth_year",
  "Q15_gender",
  "Q16_educ",
  "Q17_employ",
  "Q18_property_damage",
  "Q18_bombing",
  "Q18_steal",
  "Q18_occupied_ter",
  "Q18_emotion_violence",
  "Q18_physical_violence",
  "Q18_nothing",
  "Q18_relocation",
  "Q19_living",
  "Q20_living_before",
  "Q21_info_source",
  "Q22_family",
  "Q22_ua_media",
  "Q22_int_media",
  "Q22_social_media",
  "Q22_tv",
  "Q22_paper",
  "Q23_news_freq",
  "Q24_apps"
)

colnames(data) <- colnames
```

```{r}
#renaming options
data_clean <- data %>%
  
# 0 (always prefer delayed gains or earlier losses) 
# 15 (always prefer immediate gains or delayed losses).
  
  mutate(gain = case_when(
    str_detect(Q1, "Отримати 1600 грн прямо зараз") ~ 1,
    str_detect(Q1, "Отримати 2080 грн за 3 місяці") ~ 0)) %>% 
  
  mutate(gain_now_1 = case_when(
    str_detect(Q1_now_1, "Отримати 1600 грн прямо зараз") ~ 1,
    str_detect(Q1_now_1, "Отримати 2160 грн за 3 місяці") ~ 0)) %>% 
      
  mutate(gain_now_2 = case_when(
    str_detect(Q1_now_2, "Отримати 1600 грн прямо зараз") ~ 1,
    str_detect(Q1_now_2, "Отримати 2240 грн за 3 місяці") ~ 0)) %>% 
  
  mutate(gain_later_1 = case_when(
    str_detect(Q1_wait_1, "Отримати 1600 грн прямо зараз") ~ 1,
    str_detect(Q1_wait_1, "Отримати 2000 грн за 3 місяці") ~ 0)) %>%
  
  mutate(gain_later_2 = case_when(
    str_detect(Q1_wait_2, "Отримати 1600 грн прямо зараз") ~ 1,
    str_detect(Q1_wait_2, "Отримати 1920 грн за 3 місяці") ~ 0)) %>%
  
  mutate(pay = case_when(
    str_detect(Q2, "Заплатити 1600 грн прямо зараз") ~ 0,
    str_detect(Q2, "Заплатити 2080 грн за 3 місяці") ~ 1)) %>%
  
  mutate(pay_later_1 = case_when(
    str_detect(Q2_wait_1, "Заплатити 1600 грн прямо зараз") ~ 0,
    str_detect(Q2_wait_1, "Заплатити 2240 грн за 3 місяці") ~ 1)) %>%
  
  mutate(pay_later_2 = case_when(
    str_detect(Q2_wait_2, "Заплатити 1600 грн прямо зараз") ~ 0,
    str_detect(Q2_wait_2, "Заплатити 2160 грн за 3 місяці") ~ 1)) %>%
  
  mutate(pay_now_1 = case_when(
    str_detect(Q2_now_1, "Заплатити 1600 грн прямо зараз") ~ 0,
    str_detect(Q2_now_1, "Заплатити 2000 грн за 3 місяці") ~ 1)) %>%
  
  mutate(pay_now_2 = case_when(
    str_detect(Q2_now_2, "Заплатити 1600 грн прямо зараз") ~ 0,
    str_detect(Q2_now_2, "Заплатити 1920 грн за 3 місяці") ~ 1)) %>%
  
  ### ISSUE (HOW TO GO ABOUT THESE QUESTIONS)
  
  mutate(gain_over_time = case_when(
    str_detect(Q3_gain_time, "Отримати 1600 грн прямо зараз") ~ 1600,
    str_detect(Q3_gain_time, "Отримати 2000 грн за 3 місяці") ~ 1600,
    str_detect(Q3_gain_time, "Отримати 2400 грн за 6 місяців") ~ 2400,
    str_detect(Q3_gain_time, "Отримати 2800 грн за 9 місяців") ~ 2800,
    str_detect(Q3_gain_time, "Отримати 3200 грн за 12 місяців") ~ 3200)) %>%
  
  mutate(pay_over_time = case_when(
    str_detect(Q4_loss_time, "Заплатити 1600 грн прямо зараз") ~ -1600,
    str_detect(Q4_loss_time, "Заплатити 2000 грн за 3 місяців") ~ -2000,
    str_detect(Q4_loss_time, "Заплатити 2400 грн за 6 місяців") ~ -2400,
    str_detect(Q4_loss_time, "Заплатити 2800 грн за 6 місяців") ~ -2800,
    str_detect(Q4_loss_time, "Заплатити 3200 грн за 12 місяців") ~ -3200)) %>%
  
  mutate(Framing_gain = case_when(
    str_detect(Q5_framing, "Отримати 1600 грн прямо зараз") ~ 1600,
    str_detect(Q5_framing, "Зачекати 3 місяці та отримати 1600 грн плюс додаткові 400 грн") ~ 2000,
    str_detect(Q5_framing, "Зачекати 6 місяців та отримати 1600 грн плюс додаткові 800 грн") ~ 2400,
    str_detect(Q5_framing, "Зачекати 9 місяців та отримати 1600 грн плюс додаткові 1200 грн") ~ 2800,
    str_detect(Q5_framing, "Зачекати 12 місяців та отримати 1600 грн плюс додаткові 1600 грн") ~ 3200)) %>% 

  mutate(Magnitude = case_when(
    str_detect(Q6_magnitude, "3200 грн прямо зараз") ~ 3200,
    str_detect(Q6_magnitude, "1600 грн на місяць протягом 3 місяців") ~ 4800,
    str_detect(Q6_magnitude, "9600 грн за 6 місяців") ~ 9600)) %>% 

  #######################################################################
  
  mutate(Risk_preference = case_when(
    str_detect(Q7_prob, "Отримати 6400 грн з ймовірністю 25%") ~ 4,              
    str_detect(Q7_prob, "Отримати 3200 грн з ймовірністю 50%") ~ 3,              
    str_detect(Q7_prob, "Отримати 2500 грн з ймовірністю 67%") ~ 2,              
    str_detect(Q7_prob, "Отримати 2125 грн з ймовірністю 75%") ~ 1,              
    str_detect(Q7_prob, "Гарантовані 1600 грн") ~ 0)) %>%

  mutate(Spend_3200 = fct_recode(Q8_spending, 
                                 "savings" = "Заощадження",
                                 "debts" = "Борги, виплати",
                                 "leisure" = "Покупки, активності, розваги, подорожі/відпустка",
                                 "investment" = "Інвестиції")) %>% 

  mutate(Time_vs_Money = fct_recode(Q9_vacation_or_pay, 
                                    "additional_salary_later" = "Дві додаткові виплати тижневої зарплати без додаткової роботи в наступному 2024 році",
                                    "additional_holiday_later" = "Два додаткові тижні відпустки без зміни зарплати в наступному 2024 році",
                                    "additional_salary_now" = "Одна додаткова виплата тижневої зарплати без додаткової роботи в нинішньому 2023 році",
                                    "additional_holiday_now" = "Один додатковий тиждень відпустки без зміни зарплати в нинішньому 2023 році")) %>%
  
  mutate(Fin_expectation = fct_recode(Q10_fin_expectation, 
                                    "much_worse" = "Буде набагато гірше, ніж зараз",
                                    "worse" = "Буде дещо гірше, ніж зараз",
                                    "same" = "Буде приблизно так само",
                                    "better" = "Буде дещо краще, ніж зараз",
                                    "much_better" = "Буде набагато краще, ніж зараз")) %>%
  
  mutate(Income = fct_recode(Q11_income, 
                                    "inc_1k" = "Менше 1000",
                                    "inc_5k" = "1000 - 5000 гривень",
                                    "inc_10k" = "5000 - 10000 гривень",
                                    "inc_15k" = "10000 - 15000 гривень",
                                    "inc_20k" = "15000 - 20000 гривень",
                                    "inc_20k+" = "Більше 20000 гривень")) %>%
  
  mutate(Fin_wellbeing = fct_recode(Q12_war_fin_wellbeing, 
                                    "much_worse" = "Суттєво погіршилось",
                                    "worse" = "Дещо погіршилось",
                                    "same" = "Ніяк не змінилось",
                                    "better" = "Дещо покращилось",
                                    "much_better" = "Суттєво покращилось")) %>%
  
  mutate(Debts = fct_recode(Q13_debts, 
                                    "never" = "Я ніколи нічого не купую в кредит і не беру в борг",
                                    "pay_all" = "Зазвичай, я сплачую весь борг",
                                    "pay_min_ammount" = "Зазвичай, я роблю мінімальні платежі по боргах і відсотки списуються автоматично",
                                    "pay_percent" = "Зазвичай, мені вдається виплатити відсотки, але не весь борг",
                                    "pay_bigger_half" = "Зазвичай, я виплачую більшу частину боргу")) %>%
  
  mutate(Family_fin_wellbeing = fct_recode(Q14_family_fin_wellbeing, 
                                    "poor" = "Бідне",
                                    "low-mid" = "Нижче середнього, але не бідне",
                                    "mid" = "Середнє",
                                    "high-mid" = "Вище середнього, але не заможне",
                                    "wealthy" = "Заможне")) %>%
  
  mutate(birthyear = if_else(Q15_birth_year == 88, 1988, Q15_birth_year)) %>%
  
  mutate(Gender = ifelse(Q15_gender == "Жінка", 1, 
                         ifelse(Q15_gender == "Чоловік", 0, NA))) %>%
  
  
  mutate(EducationCompleted = fct_recode(Q16_educ, 
                                         
                                         #"Primary_educ" = "Неповна середня освіта",
                                         "Secondary_educ" = "Загальна середня освіта (середня школа)",
                                         "Technical_educ" = "Середня професійна (технікум чи коледж)",
                                         "Undergrad_Grad" = "Вища освіта (бакалавр, спеціаліст, магістрт)",
                                         "PhD" = "Докторський ступінь")) %>% 
  
  mutate(Employment = fct_recode(Q17_employ, 
                                 "Student" = "Студент денної форми навчання",
                                 "Employed full-time" = "Працюю, повна зайнятість (40+ годин в тиждень)",
                                 "Employed part-time" = "Працюю неповний робочий день (менше ніж 40 годин на тиждень)",
                                 "Not in paid employment (looking)" = "Безробітний (а) (в активному пошуку роботи)",
                                 "Not in paid employment (personal reasons)" = "Безробітний (а) (за особистими обставинами, станом здоров'я)",
                                 "Unemployed (not looking)" = "Безробітний (а) (не шукаю роботу)")) %>% 
  
  
  mutate(Property_damage = fct_recode(Q18_property_damage,
                                      "0" = "Ні",
                                      "1" = "Так",
                                      "NA" = "Не хочу відповідати")) %>% 

  mutate(Bombing = fct_recode(Q18_bombing,
                                      "0" = "Ні",
                                      "1" = "Так",
                                      "NA" = "Не хочу відповідати")) %>%
  
  mutate(Robbery = fct_recode(Q18_steal,
                                      "0" = "Ні",
                                      "1" = "Так",
                                      "NA" = "Не хочу відповідати")) %>%
  
  mutate(Occupied_territory = fct_recode(Q18_occupied_ter,
                                      "0" = "Ні",
                                      "1" = "Так",
                                      "NA" = "Не хочу відповідати")) %>%
  
  mutate(Emotional_damage = fct_recode(Q18_emotion_violence,
                                      "0" = "Ні",
                                      "1" = "Так",
                                      "NA" = "Не хочу відповідати")) %>%
  
  mutate(Physical_damage = fct_recode(Q18_physical_violence,
                                      "0" = "Ні",
                                      "1" = "Так",
                                      "NA" = "Не хочу відповідати")) %>%
  
  mutate(Forced_relocation = fct_recode(Q18_relocation,
                                      "0" = "Ні",
                                      "1" = "Так",
                                      "NA" = "Не хочу відповідати")) %>%
  
  mutate(No_war_experience = fct_recode(Q18_nothing,
                                      "0" = "Ні",
                                      "1" = "Так",
                                      "NA" = "Не хочу відповідати")) %>%  
  
  mutate(region_now = fct_recode(Q19_living,
                     "Abroad" = "За кордоном",
                     "Kyiv City" = "Місто Київ",
                     "Vinnytsia" = "Вінницька",
                     "Volyn" = "Волинська",
                     "Dnipropetrovsk" = "Дніпропетровська",
                     "Donetsk" = "Донецька",
                     "Zhytomyr" = "Житомирська",
                     "Zakarpattia" = "Закарпатська",
                     "Zaporizhia" = "Запорізька",
                     "Ivano-Frankivsk" = "Івано-Франківська",
                     "Kyiv" = "Київська",
                     "Kirovohrad" = "Кіровоградська",
                     "Luhansk" = "Луганська",
                     "Lviv" = "Львівська",
                     "Mykolaiv" = "Миколаївська",
                     "Odesa" = "Одеська",
                     "Poltava" = "Полтавська",
                     "Rivne" = "Рівненська",
                     "Sumy" = "Сумська",
                     "Ternopil" = "Тернопільська",
                     "Kharkiv" = "Харківська",
                     "Kherson" = "Херсонська",
                     "Khmelnytskyi" = "Хмельницька",
                     "Cherkasy" = "Черкаська",
                     "Chernivtsi" = "Чернівецька",
                     "Chernihiv" = "Чернігівська",
                     "Crimea" = "Автономна Республіка Крим",
                     "Sevastopol" = "Севастополь")) %>% 
  
  mutate(region_before = fct_recode(Q20_living_before,
                     "Abroad" = "За кордоном",
                     "Kyiv City" = "Місто Київ",
                     "Vinnytsia" = "Вінницька",
                     "Volyn" = "Волинська",
                     "Dnipropetrovsk" = "Дніпропетровська",
                     "Donetsk" = "Донецька",
                     "Zhytomyr" = "Житомирська",
                     "Zakarpattia" = "Закарпатська",
                     "Zaporizhia" = "Запорізька",
                     "Ivano-Frankivsk" = "Івано-Франківська",
                     "Kyiv" = "Київська",
                     "Kirovohrad" = "Кіровоградська",
                     "Luhansk" = "Луганська",
                     "Lviv" = "Львівська",
                     "Mykolaiv" = "Миколаївська",
                     "Odesa" = "Одеська",
                     "Poltava" = "Полтавська",
                     "Rivne" = "Рівненська",
                     "Sumy" = "Сумська",
                     "Ternopil" = "Тернопільська",
                     "Kharkiv" = "Харківська",
                     "Kherson" = "Херсонська",
                     "Khmelnytskyi" = "Хмельницька",
                     "Cherkasy" = "Черкаська",
                     "Chernivtsi" = "Чернівецька",
                     "Chernihiv" = "Чернігівська",
                     "Crimea" = "Автономна Республіка Крим",
                     "Sevastopol" = "Севастополь")) %>%
  
  mutate(info_family = case_when(
    str_detect(Q21_info_source, "Родичі/друзі") ~ 1,
    TRUE ~ 0)) %>%
    
  mutate(info_foreign_media = case_when(
    str_detect(Q21_info_source, "Закордонні медіа") ~ 1,
    TRUE ~ 0)) %>%
   
  mutate(info_ua_media = case_when(
    str_detect(Q21_info_source, "Українські медіа") ~ 1,
    TRUE ~ 0)) %>%
    
  mutate(info_social_media = case_when(
    str_detect(Q21_info_source, "Соціальні мережі") ~ 1,
    TRUE ~ 0)) %>%
    
  mutate(info_tv = case_when(
    str_detect(Q21_info_source, "Телевізор") ~ 1,
    TRUE ~ 0)) %>%
    
  mutate(info_magazines = case_when(
    str_detect(Q21_info_source, "Газети/Журнали") ~ 1,
    TRUE ~ 0)) %>%
  
  mutate(info_family_trust = Q22_family,
         info_ua_media_trust = Q22_ua_media,
         info_foreign_media_trust = Q22_int_media,
         info_social_media_trust = Q22_social_media,
         info_tv_trust = Q22_tv,
         info_magazines_trust = Q22_paper) %>% 

  mutate(News_frequence = fct_recode(Q23_news_freq,
                                      "never" = "Не дивлюсь новини",
                                      "1_time" = "1 раз",
                                      "5_times" = "2-5 разів",
                                      "10_times" = "6-10 разів",
                                      "10+" = "Більше 10")) %>% 
  
  mutate(whatsapp = case_when(
    str_detect(Q24_apps, "WhatsApp") ~ 1,
    TRUE ~ 0)) %>%

  mutate(instagram = case_when(
    str_detect(Q24_apps, "Інстаграм") ~ 1,
    TRUE ~ 0)) %>%
    
  mutate(viber = case_when(
    str_detect(Q24_apps, "Viber") ~ 1,
    TRUE ~ 0)) %>%
    
  mutate(telegram = case_when(
    str_detect(Q24_apps, "Telegram") ~ 1,
    TRUE ~ 0)) %>%
    
  mutate(twitter = case_when(
    str_detect(Q24_apps, "Твіттер") ~ 1,
    TRUE ~ 0)) %>%
    
  mutate(facebook = case_when(
    str_detect(Q24_apps, "Facebook") ~ 1,
    TRUE ~ 0)) %>%
    
  mutate(tiktok = case_when(
    str_detect(Q24_apps, "Тікток") ~ 1,
    TRUE ~ 0))

data_clean <- data_clean[,-c(1:45)]
```

### Checking for sus responses

```{r}
# Create a summary table
summary_table <- data_clean[,c(18:24)] %>%
  tbl_summary(by = Gender) %>%  # replace 'group_column' with the actual grouping column
  add_n() %>% 
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels()

# Print the summary table
summary_table
```
```{r}
## We estimate the anomalies rates for the five anomalies (present bias = presbias; absolute magnitude = absolmag, gain-loss asymmetry = gainloss; delay-speedup = delayspeed; subadditivity = subaddit). 
## We use answers to the three baseline sets of questions plus the answers to the common difference, subadditivity, and delay-speedup items to compute the temporal discount scores.

## Computing the rates of the five anomalies


# data_clean$score_v1 <- rowMeans(data_clean[, c("gain", "gain_now_1", "gain_now_2", "gain_later_1", "gain_later_2", "pay", "pay_later_1", "pay_later_2", "pay_now_1", "pay_now_2")], na.rm = TRUE)

data_clean$score <- rowSums(data_clean[, c("gain", "gain_now_1", "gain_now_2", "gain_later_1", "gain_later_2", "pay", "pay_later_1", "pay_later_2", "pay_now_1", "pay_now_2")], na.rm = TRUE)

data_clean$score_gains <- rowSums(data_clean[, c("gain", "gain_now_1", "gain_now_2", "gain_later_1", "gain_later_2")], na.rm = TRUE)

data_clean$score_losses <- rowSums(data_clean[, c("pay", "pay_later_1", "pay_later_2", "pay_now_1", "pay_now_2")], na.rm = TRUE)
```


```{r}
data_clean <- data_clean %>% 
  mutate(fast_news = case_when(
    News_frequence %in% c("5_times", "10_times", "10+") & (instagram == 1 | tiktok == 1 | telegram == 1) ~ 1,
    TRUE ~ 0)) %>% 
  mutate(slow_news = case_when(
    News_frequence %in% c("never", "1_time") & (twitter == 1 | facebook == 1) ~ 1,
    TRUE ~ 0))


```

```{r}
data_full <- data_clean[, c(16:33, 35, 36, 49:59)] %>% 
  na.omit()
data_full_cat <-  dummy_cols(data_full, 
           select_columns = c("Spend_3200",
                              "Time_vs_Money",
                              "Fin_expectation", 
                              "Income",
                              "Fin_wellbeing",   
                              "Debts",
                              "Family_fin_wellbeing",
                              # "birthyear", 
                              "Gender",      
                              "EducationCompleted",
                              "Employment",
                              "region_now", 
                              "region_before",
                              "News_frequence"), remove_selected_columns = T)

# library(haven)
# library(tidyverse)
# library(glmnet)
# library(plm)
# library(pls)
# library(modelr)
library(leaps)


regfit.full <- regsubsets(score ~ ., data_full_cat, nvmax = 50, really.big = T, method = "backward")
reg.summary <- summary(regfit.full)
```

```{r}
plot(reg.summary$rss, xlab = "Number of Variables",
     ylab = "RSS", type = "l")
plot(reg.summary$adjr2, xlab = "Number of Variables",
     ylab = "Adjusted RSq", type = "l")
plot(reg.summary$cp, xlab = "Number of Variables",
     ylab = "Cp", type = "l")
plot(reg.summary$bic, xlab = "Number of Variables",
     ylab = "BIC", type = "l")
```

```{r}
plot(regfit.full, scale = "r2")
plot(regfit.full, scale = "adjr2")
plot(regfit.full, scale = "Cp")
plot(regfit.full, scale = "bic")
```
```{r}
reg.summary
```

## Summary Stats



## EDA

```{r}
ggplot(data_clean, aes(Income)) +
  geom_bar() +
    labs(title = "Income distribution") +
  theme_fivethirtyeight()
```


```{r}
ggplot(data_clean, aes(Fin_wellbeing, fill = Family_fin_wellbeing)) +
  geom_bar() +
  labs(title = "Financial Wellbeing") +
  theme_fivethirtyeight()
```

```{r}
g1 <- ggplot(data_clean, aes(x = score, fill = Gender)) +
  geom_bar(position = "identity") +
  labs(title = "Score_overal") +
  theme_fivethirtyeight()

g2 <- ggplot(data_clean, aes(x = score_gains, fill = Gender)) +
  geom_bar(position = "identity") +
  labs(title = "Score_gains") +
  theme_fivethirtyeight()

g3 <- ggplot(data_clean, aes(x = score_losses, fill = Gender)) +
  geom_bar(position = "identity") +
  labs(title = "Score_losses") +
  theme_fivethirtyeight()
```

```{r}
#|message: false
#|warning: false
gridExtra::grid.arrange(g1,g2,g3, ncol = 3)
```


```{r}
ggplot(data_clean, aes(Fin_expectation, fill = Fin_wellbeing)) +
  geom_bar() +
  labs(title = "Expectation") +
  theme_bw()
```

```{r}
ggplot(data_clean, aes(x = Spend_3200, fill = as.factor(score))) +
  geom_bar() +
  labs(title = "How would you spend 3200?") +
  theme_bw()
```

## Analysis

```{r}

data_full_cat <- na.omit(data_full_cat)
mod1 <- lm(score ~ Property_damage + Bombing + Robbery + Occupied_territory + Emotional_damage + Physical_damage + Forced_relocation + whatsapp + instagram + viber + telegram + twitter + facebook + tiktok + score + Spend_3200_debts + Spend_3200_savings + Spend_3200_investment + Spend_3200_leisure + Time_vs_Money_additional_holiday_later + Time_vs_Money_additional_salary_later + Time_vs_Money_additional_holiday_now + Time_vs_Money_additional_salary_now + Fin_expectation_worse + Fin_expectation_better + Fin_expectation_much_worse + Fin_expectation_much_better + Fin_expectation_same + Income_inc_5k + Income_inc_15k + Income_inc_20k + Income_inc_10k + Income_inc_20k+ + Income_inc_1k + Fin_wellbeing_worse + Fin_wellbeing_better + Fin_wellbeing_same + Fin_wellbeing_much_worse + Fin_wellbeing_much_better + Debts_pay_percent + Debts_pay_bigger_half + Debts_pay_min_ammount + Debts_pay_all + Debts_never + Family_fin_wellbeing_poor + `Family_fin_wellbeing_high-mid` + Family_fin_wellbeing_wealthy + `Family_fin_wellbeing_low-mid` + Family_fin_wellbeing_mid + Gender_0 + Gender_1 + EducationCompleted_Undergrad_Grad + EducationCompleted_PhD + EducationCompleted_Secondary_educ + EducationCompleted_Technical_educ + `Employment_Not in paid employment (looking)` + `Employment_Not in paid employment (personal reasons)` + `Employment_Unemployed (not looking)` + `Employment_Employed part-time` + `Employment_Employed full-time` + Employment_Student + region_now_Dnipropetrovsk + region_now_Abroad + region_now_Zaporizhia + `region_now_Ivano-Frankivsk` + region_now_Kyiv + region_now_Lviv + `region_now_Kyiv City` + region_now_Odesa + region_now_Poltava + region_now_Khmelnytskyi + region_now_Cherkasy + region_now_Chernihiv + region_before_Dnipropetrovsk + region_before_Abroad + region_before_Zaporizhia + region_before_Kyiv + region_before_Lviv + `region_before_Kyiv City` + region_before_Odesa + region_before_Poltava + region_before_Khmelnytskyi + region_before_Cherkasy + region_before_Chernihiv + News_frequence_1_time + News_frequence_5_times + News_frequence_10_times + `News_frequence_10+` + News_frequence_never, data = data_full_cat)
summary(mod1, type = "text")
```
