---
title: "EDA & Regression"
author: "Vadym Yudenko"
output: 
  html_document:
    code_folding: hide
editor_options: 
  chunk_output_type: inline
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(stargazer)
library(tidyverse)
library(ggExtra)
library(ggthemes)
library(corrr)
library(corrplot)
```

```{r}
data_clean <- read.csv("data/data_pilot_clean.csv")
data <- read.csv("data/data_pilot_analysis.csv")
```


## EDA

```{r, warning=FALSE, message=FALSE, class.source = 'fold-foldable'}
g2 <- ggplot(data_clean, aes(Income, fill = Gender)) +
  geom_bar() +
    labs(title = "Income",
         x = "Monthly income",
         y = "# of responders") +
  geom_label(aes(x = -0.25, y = 10, 
                 label = "Under 20000 UAH"), 
                           hjust = 0, 
                           vjust = 0.5, 
                           colour = "#555555", 
                           fill = "white", 
                           label.size = NA, 
                           family="Garamond", 
                           size = 5) +
    geom_label(aes(x = 0.75, y = 10, 
                 label = "Over 20000 UAH"), 
                           hjust = 0, 
                           vjust = 0.5, 
                           colour = "#555555", 
                           fill = "white", 
                           label.size = NA, 
                           family="Garamond", 
                           size = 5) +
  geom_text(stat = 'count', aes(label = ..count..), vjust = -0.5, color = "black", size = 5, family = "Garamond") +
  theme_classic() +
  theme(plot.title = element_text(family = "Garamond", hjust = 0.5),
        plot.caption = element_text(family = "Garamond"),
        axis.text = element_text(family = "Garamond"),
        axis.title = element_text(family = "Garamond"),
        axis.text.x = element_blank())

data_clean$EducationCompleted <- factor(data_clean$EducationCompleted, levels = c("Secondary_educ", "Technical_educ", "Undergrad_Grad", "PhD"))

g1 <- ggplot(data_clean, aes(x = EducationCompleted, fill = Gender))  +
  geom_bar() +
    labs(title = "Completed education",
         y = "# of responders") +
  geom_text(stat = 'count', aes(label = ..count..), vjust = -0.5, color = "black", size = 5, family = "Garamond") +
  theme_classic() +
  theme(plot.title = element_text(family = "Garamond", hjust = 0.5),
        plot.caption = element_text(family = "Garamond"),
        axis.text = element_text(family = "Garamond"),
        axis.title.y = element_text(family = "Garamond"),
        axis.title.x = element_blank())

gridExtra::grid.arrange(g1,g2, ncol = 2)
```

```{r, warning=FALSE, message=FALSE, class.source = 'fold-foldable'}
#|warning: false
ggplot(data_clean, aes(x = score)) +
  geom_bar(position = "identity") +
  scale_x_continuous(breaks = seq(0, 10, 1), labels = seq(0, 10, 1)) +
  labs(title = "Overal score",
       x =  "Score",
       y = "# of responders") +
  geom_curve(aes(x = 4, y = 16, xend = 1, yend = 14),
             colour = "#555555", 
             size=1.5, 
             curvature = -0.2,
             arrow = arrow(length = unit(0.03, "npc"))) +
  geom_label(aes(x = 3, y = 17, 
                 label = "Most people preferred delayed gains 
                 and immediate losses"), 
                           hjust = 0, 
                           vjust = 0.5, 
                           colour = "#555555", 
                           fill = "white", 
                           label.size = NA, 
                           family="Garamond", 
                           size = 5) +
  theme_classic() +
  theme(plot.title = element_text(family = "Garamond", hjust = 0.5),
        axis.text = element_text(family = "Garamond"),
        axis.title = element_text(family = "Garamond"))
```

```{r, warning=FALSE, message=FALSE, class.source = 'fold-foldable'}
g3 <- ggplot(data_clean, aes(x = region_before)) +
  geom_bar() +
  labs(title = "Where did you live before Feb 24th 2022?",
       y = "# of respondents") +
  coord_flip() +
   geom_text(stat = 'count', aes(label = ..count..), hjust = -0.5, color = "black", size = 5, family = "Garamond") +
  theme_classic() +
  theme(plot.title = element_text(family = "Garamond", hjust = 0.5, size = 10),
        plot.caption = element_text(family = "Garamond"),
        axis.text.y = element_text(family = "Garamond", size = 15),
        axis.text.x = element_blank(),
        axis.title.x = element_text(family = "Garamond"),
        axis.title.y = element_blank())

g4 <- ggplot(data_clean, aes(x = region_now)) +
  geom_bar() +
  labs(title = "Where do you currently live?",
       y = "# of respondents") +
  coord_flip() +
   geom_text(stat = 'count', aes(label = ..count..), hjust = -.5, color = "black", size = 5, family = "Garamond") +
  theme_classic() +
  theme(plot.title = element_text(family = "Garamond", hjust = 0.5, size = 10),
        plot.caption = element_text(family = "Garamond"),
        axis.text.y = element_text(family = "Garamond", size = 15),
        axis.text.x = element_blank(),
        axis.title.x = element_text(family = "Garamond"),
        axis.title.y = element_blank())

gridExtra::grid.arrange(g3,g4, ncol = 2)
```

```{r, warning=FALSE, message=FALSE, class.source = 'fold-foldable'}
ggplot(data_clean, aes(x = war)) +
  geom_bar() +
  facet_wrap(~Gender) +
  labs(title = "Exposure to violence and gender",
       subtitle = "0 - Male, 1 - Female",
       caption = "Exposure here is just an aggregate
       of persons responses to war related questions") +
  theme_classic() +
   theme(plot.title = element_text(family = "Garamond", hjust = 0.5, size = 10),
         plot.caption = element_text(family = "Garamond"),
         plot.subtitle = element_text(family = "Garamond"))
```

## Analysis

```{r, warning=FALSE, message=FALSE, class.source = 'fold-foldable'}
# colnames(data)
data <- na.omit(data)
mod <- lm(score ~ ., data = data)
stargazer(mod, type = "text")
```

```{r, warning=FALSE, message=FALSE, include=FALSE}
data_rich <- data %>% 
  filter(Income == 1) 

data_poor <- data %>% 
  filter(Income == 0) 

mod_rich <- lm(score ~ ., data_rich)
mod_poor <- lm(score ~ ., data_poor)
stargazer(mod_poor, mod_rich, 
          header=FALSE,
          column.labels = c("<20k UAH", "20+k UAH"),
          type='text', 
          digits=3,
          font.size = "normalsize",
          align = TRUE,
          omit.stat=c("f", "ser"),
          column.sep.width = "-25pt")
```

```{r, warning=FALSE, message=FALSE, include=FALSE}
data_emp <- data %>% 
  filter(Employment == 1) 

data_unemp <- data %>% 
  filter(Employment == 0) 

mod_emp <- lm(score ~ ., data_emp)
mod_unemp <- lm(score ~ ., data_unemp)
stargazer(mod_unemp, mod_emp, 
          header=FALSE, 
          title="unemployed vs empployed", 
          type='text', 
          digits=2,
          font.size = "small",
          align = TRUE,
          omit.stat=c("f", "ser"),
          column.sep.width = "-25pt")
```

```{r, warning=FALSE, message=FALSE, include=FALSE}
data_male <- data %>% 
  filter(Gender == 0) 

data_female <- data %>% 
  filter(Gender == 1) 

mod_f <- lm(score ~ ., data_female)
mod_m <- lm(score ~ ., data_male)
stargazer(mod_f, mod_m, 
          header=FALSE, 
          title="female vs male", 
          type='text', 
          digits=2,
          font.size = "small",
          align = TRUE,
          omit.stat=c("f", "ser"),
          no.space=TRUE)
```

```{r, warning=FALSE, message=FALSE, include=FALSE}
data_debts <- data %>% 
  filter(Debts == 1) 

data_no_debts <- data %>% 
  filter(Gender == 0) 

mod_debts <- lm(score ~ ., data_debts)
mod_no_debts <- lm(score ~ ., data_no_debts)
stargazer(mod_debts, mod_no_debts, 
          header=FALSE, 
          title="No debts vs debts", 
          type='text', 
          digits=2,
          font.size = "small",
          align = TRUE,
          omit.stat=c("f", "ser"),
          column.sep.width = "-25pt")
```

```{r, warning=FALSE, message=FALSE, class.source = 'fold-foldable'}
correlation.matrix<-cor(data[,c(1:3,5:12)]) 
corrplot(correlation.matrix,title="Correlation Matrix")
```


```{r, class.source = 'fold-foldable'}
stargazer(mod, mod_f, mod_m, mod_emp, mod_unemp, mod_poor, mod_rich,
          column.labels = c("Full model", "Female", "Male", "employed", "unemployed", "<20k UAH", "20+k UAH"),
          covariate.labels = c("Income", "Debts", "Year of birth", "Gender", "Employment", "No war experience", "Living in Kyiv now", "Living in Kyiv before 24th", "Fast news", "Slow news", "War experience", "Expects worse", "Expects better", "Expects much worse", "Expects much better", "Expects the same", "Secondary education", "Technical education", "BSc or MSc", "PhD"),
          header=FALSE, 
          title="Regression results", 
          type='text', 
          digits=3,
          style = "aer",
          font.size = "small",
          align = TRUE,
          omit = c("Constant"),
          omit.stat=c("f", "ser"),
          no.space=TRUE)
```


```{r, warning=FALSE, message=FALSE, class.source = 'fold-foldable', output=FALSE}
# #Create a summary table
# summary_table <- data_clean[,20] %>%
#    tbl_summary() %>% 
#    modify_header(label = "Financial Wellbeing after 24th") %>% 
#    bold_labels()
#  
#  # Print the summary table
# summary_table
#  
# summary_table %>%
#    as_gt() %>%
#    gt::gtsave(filename = "fin.png")
```

```{r, warning=FALSE, message=FALSE, class.source = 'fold-foldable', output=FALSE}
# library(leaps)
# 
# regfit.full <- regsubsets(score ~ ., data, nvmax = 10, really.big = T, method = "backward")
# reg.summary <- summary(regfit.full)
# 
# plot(reg.summary$rss, xlab = "Number of Variables",
#      ylab = "RSS", type = "l")
# plot(reg.summary$adjr2, xlab = "Number of Variables",
#      ylab = "Adjusted RSq", type = "l")
# plot(reg.summary$cp, xlab = "Number of Variables",
#      ylab = "Cp", type = "l")
# plot(reg.summary$bic, xlab = "Number of Variables",
#      ylab = "BIC", type = "l")
# 
# plot(regfit.full, scale = "r2")
# plot(regfit.full, scale = "adjr2")
# plot(regfit.full, scale = "Cp")
# plot(regfit.full, scale = "bic")
# 
# reg.summary
```

